name: Deploy-CF-Test

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy-CF-Test
    steps:
      - uses: actions/checkout@v2

      - name: Publish CF
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
